import { authOptions } from "@/auth/auth-options";
import Layout from "@/components/layout/layout";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { twJoin } from "tailwind-merge";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/");
  }

  return (
    <html lang="en" className="h-full bg-white">
      <body className={twJoin(inter.className, "h-full")}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
